var namespace_app1_social_link_1_1_app1_social_link___xaml_type_info =
[
    [ "XamlMetaDataProvider", "class_app1_social_link_1_1_app1_social_link___xaml_type_info_1_1_xaml_meta_data_provider.html", "class_app1_social_link_1_1_app1_social_link___xaml_type_info_1_1_xaml_meta_data_provider" ]
];